name: family_tree
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # App Dependencies
  flutter_bloc: ^8.1.2
  easy_localization: ^3.0.3
  meta: ^1.8.0
  dio: 5.1.0
  #    Infrastructure Dependencies
  injectable: 2.1.0
  get_it: 7.2.0
  go_router: ^6.5.0
  custom_refresh_indicator: ^2.0.1
  easy_localization_loader: 1.0.1+1
  shared_preferences: ^2.0.20
  collection: ^1.17.0
  countries_flag: ^1.0.0
  flutter_chat_bubble: ^2.0.2
  permission_handler: ^10.2.0
  path_provider: ^2.1.1
  scroll_to_index: ^3.0.1

  #  Presentation Dependencies
  flutter_image_compress: ^2.0.3
  scrollable_positioned_list:
  cached_network_image: ^3.2.3
  image_picker: ^0.8.8
  azlistview: ^2.0.0
  google_fonts: ^4.0.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.4
  intl: ^0.18.0
  pin_code_fields: ^8.0.1
  flutter_secure_storage: ^8.0.0
  open_file_plus: ^3.4.1
  external_path: ^1.0.3
  video_thumbnail: ^0.5.3
  #Local Database
  uuid: ^3.0.7
  file_picker: ^6.0.0
  photo_manager: ^2.7.2

  #  Domain Dependencies
  #  Data Dependencies
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  mockito:
  flutter_custom_clippers: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: 2.1.4
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/translations/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic



